- name: Reload apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart pdns
  ansible.builtin.service:
    name: pdns
    state: restarted
    enabled: true
